---
engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
    # ... CONFIG CONTENT ...
    exclude_fingerprints:
    - 46611a9dcdfbc97ed963594a822cf4b3
    - 53af6b1590a0711e6b6d8204fef9c82f
    - cf57ca3c27caad6b61115dd37bc1fc02
    - dc0e043c56c03c2ada6c448f1958cfcb
  csslint:
    enabled: false
    checks:
      max_line_length:
        enabled: false
  coffeelint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - coffeescript
  eslint:
    enabled: false
  fixme:
    enabled: false
  rubocop:
    enabled: true
ratings:
  paths:
  - Gemfile.lock
  - "**.erb"
  - "**.haml"
  - "**.rb"
  - "**.rhtml"
  - "**.slim"
  - "**.css"
  - "**.coffee"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
exclude_paths:
- config/
- db/
- spec/
- vendor/
